In [1]:
!python3 -m pip install brainome
print("\n\nChecking brainome version number:")
!brainome --version

  Using cached numpy-1.22.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
ERROR: tensorflow 2.6.1 has requirement numpy~=1.19.2, but you'll have numpy 1.22.3 which is incompatible.
ERROR: tensorflow 2.6.1 has requirement typing-extensions~=3.7.4, but you'll have typing-extensions 4.2.0 which is incompatible.
ERROR: strym 0.4.15 has requirement numpy~=1.19.2, but you'll have numpy 1.22.3 which is incompatible.
ERROR: tensorflow-gpu 2.7.0 has requirement keras<2.8,>=2.7.0rc0, but you'll have keras 2.6.0 which is incompatible.
ERROR: tensorflow-gpu 2.7.0 has requirement tensorflow-estimator<2.8,~=2.7.0rc0, but you'll have tensorflow-estimator 2.6.0 which is incompatible.
ERROR: stable-baselines3 1.3.0 has requirement gym<0.20,>=0.17, but you'll have gym 0.21.0 which is incompatible.
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.5
    Uninstalling numpy-1.19.5:
      Successfully uninstalled numpy-1.19.5


Checking brainome version number:
b

In [2]:
!python3 -m pip install pandas

In [3]:
!brainome --help

usage: brainome [-h] [-version] [-headerless] [-target TARGET]
                [-ignorecolumns IGNORECOLUMNS] [-rank [ATTRIBUTERANK]]
                [-measureonly] [-f FORCEMODEL] [-nosplit] [-split FORCESPLIT]
                [-nsamples NSAMPLES] [-ignoreclasses IGNORELABELS]
                [-usecolumns IMPORTANTCOLUMNS] [-o OUTPUT] [-v] [-q] [-y]
                [-e EFFORT] [-biasmeter] [-novalidation] [-nofun] [-modelonly]
                [-json JSON] [-C REGULARIZATION_STRENGTH]
                input [input ...]

Brainome Table Compiler (tm)  v1.8-120-prod

Required arguments:
  input                 Table as CSV files and/or URLs or Command above

Optional arguments:
  -h                    show this help message and exit
  -version, --version   show program's version number and exit

Basic options:
  -headerless           Headerless CSV input file.
  -target TARGET        Specify target column by name or number. Default: last column of table.
  -ignorecolumns IGNORECOLUMNS
    

In [9]:
!brainome cifar10_train_data.csv --yes -o brainome_out.py -f NN


Brainome Table Compiler v1.8-120-prod
Copyright (c) 2019-2022 Brainome, Inc. All Rights Reserved.
Licensed to:                 Paul Ngo  (Evaluation)
Expiration Date:             2022-07-31   100 days left
Maximum File Size:           30 GB
Maximum Instances:           unlimited
Maximum Attributes:          unlimited
Maximum Classes:             unlimited
Connected to:                daimensions.brainome.ai  (local execution)

Command:
    btc cifar10_train_data.csv --yes -o brainome_out.py -f NN

Start Time:                 04/22/2022, 18:33 PDT

Cleaning...done. 
Splitting into training and validation...done. 
Pre-training measurements...done. 


Pre-training Measurements
Data:
    Input:                      cifar10_train_data.csv
    Target Column:              Label
    Number of instances:     100000
    Number of attributes:         8 out of 8
    Number of classes:            2

Class Balance:                
                               1: 50.00%
                           

In [23]:
!brainome cifar10_train_data.csv --yes -o brainome_out.py -f NN -nosplit -v


Brainome Table Compiler v1.8-120-prod
Copyright (c) 2019-2022 Brainome, Inc. All Rights Reserved.
Licensed to:                 Paul Ngo  (Evaluation)
Expiration Date:             2022-07-31   100 days left
Maximum File Size:           30 GB
Maximum Instances:           unlimited
Maximum Attributes:          unlimited
Maximum Classes:             unlimited
Connected to:                daimensions.brainome.ai  (local execution)

Command:
    btc cifar10_train_data.csv --yes -o brainome_out.py -f NN -nosplit -v

Start Time:                 04/22/2022, 19:52 PDT

Cleaning...done. < 1s
Splitting into training and validation...done. 1s
Pre-training measurements...done. 1m 25s


Pre-training Measurements
Data:
    Input:                      cifar10_train_data.csv
    Target Column:              Label
    Number of instances:     100000
    Number of attributes:         8 out of 8
    Number of classes:            2

Class Balance:                
                               1: 50.00%
   

In [1]:
from tensorflow import keras

2022-04-25 00:27:31.964577: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ros/noetic/lib
2022-04-25 00:27:31.964595: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [19]:
model = keras.models.Sequential()

In [20]:
model.add(keras.Input(shape=(8,)))
model.add(keras.layers.Dense(16, activation='relu'))
model.add(keras.layers.Dense(1, activation='sigmoid'))

In [21]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 16)                144       
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 17        
Total params: 161
Trainable params: 161
Non-trainable params: 0
_________________________________________________________________


In [22]:
import pandas as pd

In [23]:
raw_data = pd.read_csv("cifar10_train_data.csv")

In [24]:
X = raw_data.iloc[:,:8].to_numpy()

In [25]:
X

array([[0.80211818, 0.92904288, 0.6948095 , ..., 1.16653097, 1.12921667,
        0.85217667],
       [0.80114973, 0.93188608, 0.694646  , ..., 1.18456411, 1.159953  ,
        0.85917276],
       [1.38109553, 1.39587212, 1.24606717, ..., 1.51248622, 1.37117326,
        1.05875003],
       ...,
       [1.81546283, 1.65248346, 1.50130939, ..., 1.95464873, 1.56047535,
        1.28820598],
       [1.26218724, 1.27680779, 1.15425003, ..., 1.38154137, 1.34287763,
        1.0250144 ],
       [1.32958472, 1.2330929 , 1.10385454, ..., 1.42520332, 1.24578607,
        1.02405775]])

In [26]:
y = raw_data.iloc[:,8].to_numpy()

In [27]:
y

array([1, 0, 1, ..., 0, 1, 0])

In [28]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [29]:
model.fit(X, y, epochs=50, batch_size=10)

Epoch 1/50
10000/10000 [==============================] - 3s 308us/step - loss: 0.6890 - accuracy: 0.5350
Epoch 2/50
10000/10000 [==============================] - 3s 301us/step - loss: 0.6765 - accuracy: 0.5771
Epoch 3/50
10000/10000 [==============================] - 3s 304us/step - loss: 0.6566 - accuracy: 0.6168
Epoch 4/50
10000/10000 [==============================] - 3s 305us/step - loss: 0.6317 - accuracy: 0.6486
Epoch 5/50
10000/10000 [==============================] - 3s 301us/step - loss: 0.6025 - accuracy: 0.6821
Epoch 6/50
10000/10000 [==============================] - 3s 304us/step - loss: 0.5673 - accuracy: 0.7205
Epoch 7/50
10000/10000 [==============================] - 3s 299us/step - loss: 0.5276 - accuracy: 0.7628
Epoch 8/50
10000/10000 [==============================] - 3s 300us/step - loss: 0.4881 - accuracy: 0.8024
Epoch 9/50
10000/10000 [==============================] - 3s 257us/step - loss: 0.4540 - accuracy: 0.8308
Epoch 10/50
10000/10000 [=====================

In [30]:
w_h, b_h = model.layers[0].get_weights()

In [31]:
w_o, b_o = model.layers[1].get_weights()

In [32]:
w_h

array([[ 1.3640354 , -0.10273784, -0.6751391 , -0.3581928 , -0.13853669,
         0.85019916, -0.4746667 , -0.2997676 ,  0.7618899 ,  0.89988965,
        -0.3690588 , -0.5100057 , -0.46425712,  0.09240746,  0.19627994,
         0.7246859 ],
       [-2.0665596 ,  1.3648514 ,  1.1946207 , -0.2906499 , -0.4653932 ,
        -1.7017239 ,  0.25025582, -0.26208842, -1.1886315 , -1.7089199 ,
         0.42861348, -0.51174307,  0.20051289, -0.0206387 ,  1.6312796 ,
        -1.4796364 ],
       [-0.22636682,  0.09247222, -0.43782812,  0.32508707, -0.4341849 ,
         0.3516699 ,  0.21297944,  0.30395257, -0.21749139, -0.2517772 ,
        -0.36406204,  0.20887908, -0.41264272, -0.35000634,  0.4220969 ,
        -0.10533819],
       [ 0.09742023,  0.36949804,  0.5124769 , -0.26852143,  0.0244813 ,
        -0.1209502 ,  0.10416758, -0.28383029,  0.3219538 ,  0.29377377,
        -0.3809956 , -0.00616221, -0.39392388, -0.46517754, -0.16641705,
        -0.2446984 ],
       [-0.04845894,  0.37403715,  0

In [33]:
b_h

array([-0.01367188,  0.1735035 ,  0.14396368,  0.        ,  0.        ,
        0.28711557,  0.        ,  0.        , -0.09063929, -0.2810001 ,
       -0.04962711, -0.03020805,  0.        ,  0.        ,  0.27157122,
        0.01795548], dtype=float32)

In [34]:
w_o, b_o

(array([[-3.5722569e+01],
        [ 1.3087072e+00],
        [ 1.5581534e+00],
        [ 4.3456006e-01],
        [ 4.2737460e-01],
        [-4.7071443e+00],
        [-3.5133514e-01],
        [ 2.6661325e-01],
        [-9.3276072e+00],
        [-6.7452927e+00],
        [-4.4879299e-01],
        [ 1.1720100e-02],
        [ 3.5361540e-01],
        [-1.8780094e-01],
        [ 2.3053513e+00],
        [-3.3297791e+01]], dtype=float32),
 array([0.36210632], dtype=float32))